## SelectK _Regression - Best Model

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split 
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from sklearn.metrics import r2_score
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
import pickle
import matplotlib.pyplot as plt

In [2]:
def selectkbest(indep_x,dep_y,n):
    SK = SelectKBest(score_func = chi2, k=n)
    SKfit = SK.fit(indep_x,dep_y)
    selectedk_features = SK.transform(indep_x)
    selected_indices = SK.get_support(indices=True)
    selected_features_names = indep_x.columns[selected_indices]
    return selectedk_features, selected_features_names.tolist()

In [3]:
def split_scaler(indep_x,dep_y):
    x_train,x_test,y_train,y_test = train_test_split(indep_x,dep_y,test_size = 0.2,random_state = 0)
    sc = StandardScaler()
    x_train = sc.fit_transform(x_train)
    x_test = sc.transform(x_test)
    return x_train,x_test,y_train,y_test,sc

def R2_prediction(regressor,x_test,y_test):
    y_pred = regressor.predict(x_test)

    R2_score = r2_score(y_test,y_pred)
    return regressor,R2_score

def decision(x_train,y_train,x_test,y_test):
    regressor = DecisionTreeRegressor(random_state=0)
    regressor.fit(x_train,y_train)
    return R2_prediction(regressor,x_test,y_test)  

In [4]:
def selectK_regression(r2dc):
    SKdataframe = pd.DataFrame(index = ['Chisquare'], columns = ['Decision'])
    SKdataframe['Decision'] = r2dc
    return SKdataframe

In [5]:
dataset = pd.read_csv("CKD.csv",index_col=None)
dataset

age         bp sg   al   su     rbc        pc         pcc  \
0     2.000000  76.459948  c  3.0  0.0  normal  abnormal  notpresent   
1     3.000000  76.459948  c  2.0  0.0  normal    normal  notpresent   
2     4.000000  76.459948  a  1.0  0.0  normal    normal  notpresent   
3     5.000000  76.459948  d  1.0  0.0  normal    normal  notpresent   
4     5.000000  50.000000  c  0.0  0.0  normal    normal  notpresent   
..         ...        ... ..  ...  ...     ...       ...         ...   
394  51.492308  70.000000  a  0.0  0.0  normal    normal  notpresent   
395  51.492308  70.000000  c  0.0  2.0  normal    normal  notpresent   
396  51.492308  70.000000  c  3.0  0.0  normal    normal  notpresent   
397  51.492308  90.000000  a  0.0  0.0  normal    normal  notpresent   
398  51.492308  80.000000  a  0.0  0.0  normal    normal  notpresent   

             ba         bgr  ...        pcv            wc        rc  htn   dm  \
0    notpresent  148.112676  ...  38.868902   8408.191126  4.705597   no   no   
1    notpresent  148.112676  ...  34.000000  12300.000000  4.705597   no   no   
2    notpresent   99.000000  ...  34.000000   8408.191126  4.705597   no   no   
3    notpresent  148.112676  ...  38.868902   8408.191126  4.705597   no   no   
4    notpresent  148.112676  ...  36.000000  12400.000000  4.705597   no   no   
..          ...         ...  ...        ...           ...       ...  ...  ...   
394  notpresent  219.000000  ...  37.000000   9800.000000  4.400000   no   no   
395  notpresent  220.000000  ...  27.000000   8408.191126  4.705597  yes  yes   
396  notpresent  110.000000  ...  26.000000   9200.000000  3.400000  yes  yes   
397  notpresent  207.000000  ...  38.868902   8408.191126  4.705597  yes  yes   
398  notpresent  100.000000  ...  53.000000   8500.000000  4.900000   no   no   

     cad  appet    pe  ane classification  
0     no    yes   yes   no            yes  
1     no    yes  poor   no            yes  
2     no    yes  poor   no            yes  
3     no    yes  poor  yes            yes  
4     no    yes  poor   no            yes  
..   ...    ...   ...  ...            ...  
394   no    yes  poor   no            yes  
395   no    yes  poor  yes            yes  
396   no   poor  poor   no            yes  
397   no    yes  poor  yes            yes  
398   no    yes  poor   no             no  

[399 rows x 25 columns]

In [6]:
df = dataset

In [7]:
df = pd.get_dummies(df,dtype=int,drop_first=True)

In [8]:
indep_x = df.drop('classification_yes',axis=1)
dep_y = df['classification_yes']

In [9]:
kbest, selected_feature_names = selectkbest(indep_x,dep_y,8)

r2dc = []

In [10]:
kbest

array([[2.00000000e+00, 3.00000000e+00, 1.48112676e+02, ...,
        1.25181556e+01, 3.88689024e+01, 8.40819113e+03],
       [3.00000000e+00, 2.00000000e+00, 1.48112676e+02, ...,
        1.07000000e+01, 3.40000000e+01, 1.23000000e+04],
       [4.00000000e+00, 1.00000000e+00, 9.90000000e+01, ...,
        1.20000000e+01, 3.40000000e+01, 8.40819113e+03],
       ...,
       [5.14923077e+01, 3.00000000e+00, 1.10000000e+02, ...,
        9.10000000e+00, 2.60000000e+01, 9.20000000e+03],
       [5.14923077e+01, 0.00000000e+00, 2.07000000e+02, ...,
        8.50000000e+00, 3.88689024e+01, 8.40819113e+03],
       [5.14923077e+01, 0.00000000e+00, 1.00000000e+02, ...,
        1.63000000e+01, 5.30000000e+01, 8.50000000e+03]])

In [11]:
selected_feature_names

['age', 'al', 'bgr', 'bu', 'sc', 'hrmo', 'pcv', 'wc']

In [12]:
x_train,x_test,y_train,y_test,sc = split_scaler(kbest,dep_y)

In [13]:
regressor,R2_score = decision(x_train,y_train,x_test,y_test)
r2dc.append(R2_score)

In [14]:
r2dc

[0.8958333333333334]

In [15]:
result = selectK_regression(r2dc)

In [16]:
result

Decision
Chisquare  0.895833

In [17]:
import pickle

filename = 'Finalized_Decision_Model.sav'

In [18]:
pickle.dump(regressor,open(filename, 'wb'))

In [19]:
filenamesc = 'sc.pkl'

In [20]:
sc = pickle.dump(sc,open(filenamesc,'wb'))

In [21]:
sc = pickle.load(open('sc.pkl','rb'))

In [23]:
user_input = sc.transform([[32, 2.0, 148.11, 17, 1.7, 14.6, 52, 6900]])
user_input

array([[-1.24492348,  0.91842938, -0.01533156, -0.82516364, -0.25895875,
         0.79130636,  1.61244852, -0.59094013]])

In [24]:
loaded_model = pickle.load(open('Finalized_Decision_Model.sav','rb'))
Prediction = loaded_model.predict(user_input)

In [28]:
Prediction = Prediction.astype('int64')

In [29]:
Prediction

array([1], dtype=int64)